# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'eventmachine'
require 'em-systemcommand'

EventMachine.instance_eval do
  def assertions time = 1
    EM.add_timer(time) do
      EM.stop_event_loop
      yield
    end
  end
end unless EM.respond_to?(:assertions)

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end
